language: go
go:
  - 1.6
  - 1.5

install: make install_ci

env:
  - RUN="make lint"
  - RUN="make test-unit"
  - RUN="make test-integration"
  - RUN="make test-race"

matrix:
  allow_failures:
    - env: RUN="make test-race"
  fast_finish: true

script:
  - test/travis

after_success:
  - test/update-coveralls

cache:
  directories:
    - $HOME/.glide/cache
